### ISSUE TITLE
iTunes

### ISSUE THREAD

**Issue by blackcrater** [danleech/simple-icons#110]
These are great, thanks!

How about an icon for the iTunes Store (not just the Apple icon)?  Thanks!

**Comment by danleech** [comment]
I’m going to close this issue for two reasons.

1) I can’t find a vector source to work from.
2) Apple asks users not to use the iTunes icon, but rather the Apple icon ([see here](http://www.apple.com/itunes/marketing-on-itunes/identity-guidelines.html#itunes-badge)).
