### ISSUE TITLE
Can u please add 'Bing,sound cloud and Saucelabs' icons

### ISSUE THREAD

**Issue by nachiketk21** [danleech/simple-icons#144]
For bing - http://www.bing.com/
For Sound cloud - https://soundcloud.com/
For sauce labs - http://support.saucelabs.com/home

**Comment by ManuelGotzen** [comment]
Which bothers me a lot now so what design and precision as well as aesthetics are concerned. 
Therefore, I simply times taken the last hour and created two new SoundCloud Logo. 
Perfect would defenitiv different. But that may not give you those.

PDF Preview: http://manuelgotzen.de/lib/git/icn/soundcloud-2015-10-22.pdf
AI Source: http://manuelgotzen.de/lib/git/icn/soundcloud-2015-10-22.ai

Color Management ist from original current CSS.
