### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by davidbauer** [danleech/simple-icons#166]
Medium, Kippt, Speakerdeck, Storify

**Comment by danleech** [comment]
###### Done
- Medium
- Zillow

###### Not going to do
- ActiveRain
- Kippt (closed down)
- PDF
- RealBird
- Trover
- ZIP

###### Separate issues
- [Everplaces](https://github.com/danleech/simple-icons/issues/218)
- [Excel](https://github.com/danleech/simple-icons/issues/221)
- [Houzz](https://github.com/danleech/simple-icons/issues/219)
- [Magento](https://github.com/danleech/simple-icons/issues/223)
- [Speaker Deck](https://github.com/danleech/simple-icons/issues/134)
- [Storify](https://github.com/danleech/simple-icons/issues/224)
- [PowerPoint](https://github.com/danleech/simple-icons/issues/222)
- [Trulia](https://github.com/danleech/simple-icons/issues/217)
- [Word](https://github.com/danleech/simple-icons/issues/220)
