### ISSUE TITLE
Mac system icons

### ISSUE THREAD

**Issue by felixphew** [danleech/simple-icons#167]
Ideally, it would be great if all the mac system applications (see below) were in this icon set so that they could be used for all my mac apps!

This is a list of the required icons (to start):
```
App Store
Automator
Calculator
Calendar
Chess
Contacts
Dashboard
Dictionary
DVD Player
FaceTime
Font Book
Game Center
GarageBand
iBooks
Image Capture
iMovie
iPhoto
iTunes
Keynote
Launchpad
Mail
Maps
Messages
Mission Control
Notes
Numbers
Pages
Photo Booth
Preview
QuickTime Player
Reminders
Safari
Stickies
System Preferences
TextEdit
Time Machine
Activity Monitor
AirPort Utility
AppleScript Editor
Audio MIDI Setup
Bluetooth File Exchange
Boot Camp Assistant
ColorSync Utility
Console
DigitalColor Meter
Disk Utility
Grab
Grapher
Keychain Access
Migration Assistant
System Information
Terminal
VoiceOver Utility
XQuartz
```
I understand that this is a lot of icons, and will be a gradual process, but I hope that eventually they could all end up in there.

**Comment by danleech** [comment]
Not going to go this deep. I have an Apple icon, and I may add an iTunes one in the future, but that’s it.
