### ISSUE TITLE
Request: Meetup

### ISSUE THREAD

**Issue by si** [danleech/simple-icons#169]
It would be great if you included Meetup – another social meeting site.

I've just created a 512px version (attached) with the hex code F20017.
![meetup-512](https://f.cloud.github.com/assets/18108/2372101/5b3e7a74-a835-11e3-82b3-f3e0eac23a36.png)

**Comment by danleech** [comment]
This is in the dev branch, ready to go into the next release. I couldn’t find an official vector of their logo (which is really, really bad at small sizes) so I had to put one together myself. I may revisit this.
