### ISSUE TITLE
Deezer and Google Play

### ISSUE THREAD

**Issue by esevece** [danleech/simple-icons#170]
I'm using Simple Icons for the website of a music duo.
It would be great to have the icons for Deezer (https://developers.deezer.com/guidelines/logo) and Google Play in the collection.
I'm not a designer, so I can't help designing them.

**Comment by danleech** [comment]
I can’t find an official monochrome Google Play icon at the moment. If one is made available by Google I’ll add it.

**Comment by victoriafrench** [comment]
like this one? https://playo.co/img/button_appstore_android.svg There are a
bunch of these in use (white, gray, black).

**Comment by danleech** [comment]
@victoriafrench *Exactly* like that one. Any idea if it’s endorsed by Google, or is it just an artistic interpretation?

**Comment by victoriafrench** [comment]
From what I can tell in the docs, the only “official” google play logo is
the physical button in it’s entirety with text and in color. The one I sent
earlier is in use today by others and is the one included in a Sketch
package.

I would suggest making the monochrome logo and then submitting it to Google
for approval (https://support.google.com/googleplay/contact/brand_developer).
It takes them less than a week to approve or deny requests. I am sure they
would accept the logo if it is pointed out that the apple logo is also in
the stack and “abiding by making the google play logo the same size” would
render it unreadable or recognizable to the end user.
