### ISSUE TITLE
Ohloh icon request

### ISSUE THREAD

**Issue by jubalh** [danleech/simple-icons#181]
An icon for [ohloh](https://www.ohloh.net/) would be great, you can see their favicon when you go to their and [here](http://www.fullcontact.com/wp-content/themes/fullcontact/assets/images/social/ohloh.png) I wound a similar one.

**Comment by danleech** [comment]
I can’t figure this one out. It seems like there’s been an acquisition or rebrand since the issue was created. I’m going to close this.
