### ISSUE TITLE
Request: Campaign Monitor

### ISSUE THREAD

**Issue by craftified** [danleech/simple-icons#206]
Thanks, for these awesome icons Dan.

**Comment by danleech** [comment]
A Campaign Monitor icon is in the [dev branch](https://github.com/danleech/simple-icons/blob/dev/icons/campaignmonitor.svg). A monochrome version of MailChimp’s Freddie is going to take a little more effort though!

**Comment by danleech** [comment]
I’ve added a separate issue for MailChimp. https://github.com/danleech/simple-icons/issues/213
