### ISSUE TITLE
Request: Windows

### ISSUE THREAD

**Issue by danleech** [danleech/simple-icons#228]

**Comment by cmcky** [comment]
@danleech A number of these issues are tagged as closed but are still Open, is it just that you haven't pushed them live yet? Or do you still need help with these?

**Comment by danleech** [comment]
I’m in the process of tidying up the requests. The project was idle for a couple of years before this week’s refresh (in which I scrapped everything and started again). Some icons that were in the previous PNG set are not present in the new SVG set, so it’s entirely possible some closed issues are now valid again.

I’ll be adding more and more icons over time. If there’s something you want (Windows, for example) make sure there’s an open issue for it. Please avoid grouping requests together though, it makes ticking them off difficult. One issue per icon request, and as many of them as you want :)
