### ISSUE TITLE
Request: Google+

### ISSUE THREAD

**Issue by patrickhlauke** [danleech/simple-icons#233]
https://plus.google.com/+googleplus/posts/HxBQHvQbywE

**Comment by danleech** [comment]
Look closer... it’s already there.

**Comment by patrickhlauke** [comment]
oops, my bad...i stupidly looked on https://simpleicons.org/ next to the G, rather than going by color.

**Comment by danleech** [comment]
Sorting options might happen soon. There’s a lot of icons there now! For now, use Cmd+F to find text on the page.
