### ISSUE TITLE
SoundCloud Optimize 

### ISSUE THREAD

**Issue by ManuelGotzen** [danleech/simple-icons#234]
Which bothers me a lot now so what design and precision as well as aesthetics are concerned. 
Therefore, I simply times taken the last hour and created two new SoundCloud Logo. 
Perfect would defenitiv different. But that may not give you those.

PDF Preview: http://manuelgotzen.de/lib/git/icn/soundcloud-2015-10-22.pdf
AI Source: http://manuelgotzen.de/lib/git/icn/soundcloud-2015-10-22.ai

Color Management ist from original current CSS.
![image](https://cloud.githubusercontent.com/assets/8329497/10650604/aadad0fa-784a-11e5-9535-1177441e8631.png)

**Comment by danleech** [comment]
Ugh, @soundcloud. We need a vector image format that allows display size breakpoints to accommodate designers who don’t have the confidence to scale their logo without tinkering with it.

I will consider this update, but it’s a low priority. I’ve tried to use official vector artwork in this set, and the only one SoundCloud provides is their “full size” logo intended for print.

**Comment by ManuelGotzen** [comment]
You can Download it here http://manuelgotzen.de/lib/git/icn/soundcloud-2015-10-22.ai
The PNG was only a preview. The Vectors are clean.

**Comment by ManuelGotzen** [comment]
But i can also optimze it in a perferct form if you like.

**Comment by ManuelGotzen** [comment]
ff3500: 
![soundcloud-ff3500](https://cloud.githubusercontent.com/assets/8329497/10884344/e4ab54ea-8177-11e5-827e-e68005fb8b68.png)

ff7700: 
![soundcloud-ff7700](https://cloud.githubusercontent.com/assets/8329497/10884343/e4973604-8177-11e5-9957-2bc9379e77b2.png)

source: 
SVG: http://manuelgotzen.de/lib/git/icn/soundcloud.svg
ASE Colortable: http://manuelgotzen.de/lib/git/icn/soundcloud.ase

**Comment by danleech** [comment]
I’ll revisit this if Soundcloud ever publishes guidelines for scalable artwork on the web.
