### ISSUE TITLE
Check in a LICENSE file to GitHub

### ISSUE THREAD

**Issue by jawnsy** [danleech/simple-icons#236]
Hi,

Thanks for producing such gorgeous icons and releasing them under an open-source license!

I see the following statement on the [official web site for the icons](https://simpleicons.org/):

> DISTRIBUTED FOR FREE BY DAN LEECH UNDER THE FREE ART LICENSE.

It would be nice to add a statement to the README indicating the license and also have a copy of it as a LICENSE file. This is standard practice on GitHub and will help others understand their rights and obligations with respect to their use of your icons. It may even encourage other designers to contribute.

Cheers,

Jonathan

**Comment by danleech** [comment]
@jawnsy Thanks for pointing this out. I’m prepping a LICENSE file now.
