### ISSUE TITLE
Request: Amazon

### ISSUE THREAD

**Issue by rowe-morehouse** [danleech/simple-icons#237]
It's funny how Amazon always gets left out of these types of collections! ... they are such a huge player on the internet, but people seem to ignore them when it comes to icon sets. :)

GREAT work by the way! ... love it.

**Comment by danleech** [comment]
@rowe-morehouse Not an oversight, I just can’t find an *official* “A” icon in vector format. As far as I can tell Amazon only make the full “Amazon” logo available. Will update if this changes, or if someone can send me a link!

**Comment by danleech** [comment]
I’ll use this in the next release. https://worldvectorlogo.com/logo/amazon-icon
