### ISSUE TITLE
Payment icons: Visa, MasterCard, American Express, etc.

### ISSUE THREAD

**Issue by wsmd** [danleech/simple-icons#254]

**Comment by cmcky** [comment]
@wsmd These should be created as separate requests. @danleech How do you want to approach these? Do you want a bounding box to mimic a card, or do you want the actual corporate logos. 
1. MasterCard uses a separate logo for corporate than it uses on cards. 
2. How to approach color for MasterCard and Amex?
<img width="635" alt="screen shot 2015-10-29 at 8 29 39 pm" src="https://cloud.githubusercontent.com/assets/5117005/10835810/a4072ff2-7e7c-11e5-80b7-6b84b0f041d8.png">

Here is what I have so far:

**Comment by danleech** [comment]
@cmcky MasterCard provides single colour assets [here](https://www.mastercardbrandcenter.com/us/getourbrand/index.shtml?pageId=dl_1230). I’ll probably go with MasterCard red (defined [here](https://www.mastercardbrandcenter.com/mcbrand/us/downloadAsset.do?fileLoc=img.dl_1510.stnd.4) as #CC0000) as the colour. Visa and Amex brand sites are private; where did you get your assets from?

**Comment by cmcky** [comment]
https://commons.wikimedia.org/wiki/File:Visa_2014_logo_detail.svg

https://commons.wikimedia.org/wiki/File:American_Express_logo.svg

https://www209.americanexpress.com/merchant/services/en_US/pages/logosandsupplies/downloadsTerms?logoItemNo=Amex_Gradient&itemType=Downloads&elogoFileName=AMEX_Gradient.zip

Both need cleaning up and a bit of reworking, but are a good start.
