### ISSUE TITLE
hex color code letter should be in lowercase

### ISSUE THREAD

**Issue by athimannil** [danleech/simple-icons#275]
https://google.github.io/styleguide/htmlcssguide.xml?showone=Block_Content_Indentation#Capitalization

https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss

**Comment by danleech** [comment]
I can’t find any technical justification for picking either lowercase or uppercase for hexadecimal values. It seems to be an aesthetic decision. I do, however, see that if anyone is currently string matching using `simple-icons.json` as a data source then it’s useful to be consistent.

I’ll leave this issue open for a bit in case anyone can show that lowercase has a technical advantage.

**Comment by athimannil** [comment]
@danleech I think there is no technical reason to keep color code in upper or lower case its actually perfectly valid to even combine these to
```
  color: #ffffff;
  color: #FfFfFf;
  color: white;
```
