### ISSUE TITLE
Include implementation example

### ISSUE THREAD

**Issue by nk8** [danleech/simple-icons#285]
There are several ways to implement SVG icons. It would be nice to have an "examples" directory to showcase best practice methods for implementation, including compiling needed SVG icons into sprite.

**Comment by danleech** [comment]
Great idea!

**Comment by danleech** [comment]
Maybe I could open up the repo wiki and put examples in there. Seems like an appropriate use for it.

**Comment by danleech** [comment]
Oh, FYI I’d advise against spriting in favour of embedding SVG code directly in your HTML (manually copy and paste, or import using your build script). That way you can target paths using CSS, like:

```sass
.icon--twitter {
    path {
        fill: #55ACEE;
    }
}
```

**Comment by danleech** [comment]
https://github.com/danleech/simple-icons/wiki
