### ISSUE TITLE
filename in json

### ISSUE THREAD

**Issue by hurt138** [danleech/simple-icons#288]
Any reason the icon filename could not be added to the json file?

**Comment by Wouter0100** [comment]
Indeed, this would be awesome.

**Comment by danleech** [comment]
I see where you’re coming from, but I don’t want the maintenance overhead of having both title and filename in the JSON. In my [build script](https://github.com/danleech/simple-icons/blob/gh-pages/src/build.js) I use this bit of JavaScript to create filenames:

```javascript
for (var i = 0; i < source.icons.length; i++) {
    var fileName = source.icons[i].title.toLowerCase();
    fileName = fileName.replace(/[!|’|.| ]/g, ''); // Replace bang, apostrophe, period and space with nothing.
    fileName = fileName.replace(/[+]/, 'plus'); // Replace the plus symbol with “plus”.

    // Do something with $fileName here
}
```

Could you use something similar?
