### ISSUE TITLE
Zip-file of all Icons

### ISSUE THREAD

**Issue by mdriesen** [danleech/simple-icons#297]
Please.

**Comment by Wouter0100** [comment]
[It's magic.](https://github.com/danleech/simple-icons/archive/gh-pages.zip)

**Comment by mdriesen** [comment]
Wow! That was quick! Thanks a lot! :-)YoursMarcus
 

    Wouter van Os <notifications@github.com> schrieb am 9:32 Montag, 15.Februar 2016:
 
 

 It's magic.—
