### ISSUE TITLE
Request: Google Hangouts

### ISSUE THREAD

**Issue by slaughter550** [danleech/simple-icons#301]
https://hangouts.google.com/

http://www.brandsoftheworld.com/sites/default/files/styles/logo-thumbnail/public/112013/hangouts_0.png?itok=reYr0Z3x

https://sites.google.com/a/pressatgoogle.com/google-i-o-press-2013/_/rsrc/1368086422165/Images/Hangouts%20on%20Air%20Logo.jpg?height=200&width=200

**Comment by Wouter0100** [comment]
Oeh. Nice one.

**Comment by Wouter0100** [comment]
Vector available at https://worldvectorlogo.com/logo/google-hangouts

**Comment by slaughter550** [comment]
That's perfect! Is it possible for you to do the hangouts on air one (yellow)?

![Hangout on Air](https://sites.google.com/a/pressatgoogle.com/google-i-o-press-2013/_/rsrc/1368086422165/Images/Hangouts%20on%20Air%20Logo.jpg?height=2000&width=2000)

**Comment by slaughter550** [comment]
@Wouter0100 mention ^

**Comment by danleech** [comment]
I’m waiting for Google to make public a vector version of the current Hangouts icon (below) rather than implement this old style icon.

![Google Hangouts logo](https://ssl.gstatic.com/images/icons/material/product/2x/hangouts_32dp.png)

**Comment by FletchXYZ** [comment]
Must all logos submitted be solid, with no gray/other tones, @danleech?

**Comment by danleech** [comment]
@FletchXYZ SVG paths should not have a colour attribute set, which precludes multiple shades or gradients.
