### ISSUE TITLE
Request: Text editor icons

### ISSUE THREAD

**Issue by birjolaxew** [danleech/simple-icons#351]
Atom (already SVG): <p align="center"><img src="https://upload.wikimedia.org/wikipedia/commons/8/80/Atom_editor_logo.svg" title="Atom" width="128px" /></p>

Sublime Text: <p align="center"><img src="https://upload.wikimedia.org/wikipedia/en/4/4c/Sublime_Text_Logo.png" title="Sublime Text" width="128px" /></p>

Visual Studio Code: <p align="center"><img src="https://code.visualstudio.com/images/favicon.ico" title="Visual Studio Code" width="128px" /></p>

WebStorm (already SVG): <p align="center"><img src="https://cdn.worldvectorlogo.com/logos/webstorm-icon.svg" title="WebStorm" width="128px" /></p>

**Comment by donroyco** [comment]
Note: the Sublime Text icon has been updated recently.
