### ISSUE TITLE
Request: Umbra

### ISSUE THREAD

**Issue by danleech** [danleech/simple-icons#363]
Request from https://twitter.com/readingdancer/status/844872094127198208

SVG artwork available at https://umbraco.com

**Comment by bjarnef** [comment]
You can download the logo here: https://umbraco.com/blog/new-umbraco-identity/

**Comment by donroyco** [comment]
The link on the page @bjarnef provided is not available (anymore):

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by bjarnef** [comment]
@donroyco the link works fine too me.

![image](https://cloud.githubusercontent.com/assets/2919859/25308361/97b3e4f8-27b2-11e7-853c-2ff1f0255f17.png)

**Comment by bjarnef** [comment]
@donroyco ahh, sorry .. the link to the download (.zip) isn't available. https://umbraco.com/assets/umbraco_logos.zip

**Comment by donroyco** [comment]
@bjarnef The actual .zip link/file behind _download the new logo and logotype as illustrator files here_ is not working (anymore).

**Comment by bjarnef** [comment]
Maybe save the Umbraco svg icon in same base size as the other icons, e.g. for WordPress
https://github.com/danleech/simple-icons/blob/6cf875c669e518c7a1e5b9089e9965b4488f3fd9/icons/wordpress.svg

https://github.com/danleech/simple-icons/blob/6cf875c669e518c7a1e5b9089e9965b4488f3fd9/icons/umbraco.svg

**Comment by danleech** [comment]
@bjarnef Well spotted, thanks! The difference is the `width=16` and `height=16` attributes on the Umbraco icon (and many others in the set). They shouldn’t impact usage, as CSS overrides these values, but I’ll remove them for now.

At some point soon I’m going to remaster the whole icon set at 24x24px, using Google’s [Material Icons guidelines](https://material.io/guidelines/style/icons.html) for scaling different shapes. This should make the whole set more harmonious.
