### ISSUE TITLE
Feature request : Search for Company Name

### ISSUE THREAD

**Issue by ibrent** [danleech/simple-icons#376]
Now that you've reached a plentiful logo+company count, a simple search at the top of the page might be a nice feature.

**Comment by danleech** [comment]
You’re not the only person to ask for this feature to be put back. I’ll build search into the next big version of Simple Icons (coming soon, once [CSS grid](http://caniuse.com/#search=grid) hits critical mass). Until then,
 use <kbd>⌘F</kbd> on the page to search.
