### ISSUE TITLE
Should we specify 'width="16" height="16"' in submitted logos?

### ISSUE THREAD

**Issue by rosslh** [danleech/simple-icons#382]
I know the old readme asked for a 16x16 viewbox for the logos, but the actual width/height values are inconsistent between logos, which makes some logos look like [this](https://simpleicons.org/icons/upwork.svg) when clicked and others like [this](https://simpleicons.org/icons/discord.svg).

**Comment by danleech** [comment]
Well spotted! Yes, this is an inconsistency that bugs me. Ideally, there should be a viewbox specified but no height or width. For most icons that means an opening SVG tag that looks like this:

```html
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd">
```

I’m planning a major overhaul very soon (now the collection has hit 300 icons 🎉). Part of that will be revisiting all sources to check if icons are still up-to-date and recreating them in a 24×24 viewbox using the icon grid specified in the [Material Design docs](https://material.io/guidelines/style/icons.html#icons-system-icons).
