### ISSUE TITLE
Icons fonts

### ISSUE THREAD

**Issue by Soullivaneuh** [danleech/simple-icons#388]
Are you planning to add font icons support as FontAwesome for example?

**Comment by danleech** [comment]
No, but if you want an icon font with Simple Icons glyphs you can generate one with [IcoMoon](https://icomoon.io/app/#/select). There are good reasons why I won’t be offering an icon font:

**Performance issues with icon fonts**

- Your user needs to download every single glyph before one can be rendered. For Simple Icons that means 300 brand icons (~100kB), most of which you’re probably not using.
- Your user is caching the entire glyph set in a single file, so changing one glyph invalidates the whole cache.
- HTTP/2 (now at [80% support](https://caniuse.com/#search=http%2F2)) favours multiple, small files (like SVGs).

**Accessibility issues with icon fonts**

- If an icon font can’t or won’t load, there’s no graceful fallback (unless you use custom ligatures).
- You have no control over users with user stylesheets, which may override your icon fonts (e.g. dyslexic people using weighted fonts).
- Screen readers will not read icon font glyphs (unless you add `aria-label` attributes to your icon elements).

**Comment by ericcornelissen** [comment]
I'll just point out [this project](https://github.com/yammadev/brand-icons) (as seen in #478) for anyone interested in this
