### ISSUE TITLE
Request: Addthis

### ISSUE THREAD

**Issue by redpik** [danleech/simple-icons#394]
SVG here:

`
<svg xmlns="http://www.w3.org/2000/svg" height="25" width="25" version="1.1" viewBox="0 0 25 25">
	<path d="m18.8 14.1h-4.7v4.69h-3.1v-4.7h-4.8v-3.18h4.7v-4.72h3.1v4.72h4.7zm3.1-14.1h-18.8c-1.68-0.04-3.1 1.37-3.1 3.08v18.8c0 1.7 1.41 3.1 3.14 3.1h18.8c1.72 0 3.14-1.41 3.14-3.12v-18.8c0-1.72-1.41-3.12-3.14-3.12z"/>
</svg>
`

**Comment by donroyco** [comment]
For the record:
```
        {
            "title": "AddThis",
            "hex": "FF5C3E",
            "source": "http://www.addthis.com/press"
        },
```

Color via [website AddThis](http://www.addthis.com/press).

**Comment by donroyco** [comment]
@redpik Your SVG has a fixed height and width. It should be without them and with a viewBox of `0 0 16 16`. Unfortunately, I can't open the .eps from the AddThis website to make a pull request.
