### ISSUE TITLE
Request: Fedora

### ISSUE THREAD

**Issue by joseluisq** [danleech/simple-icons#412]
https://fedoraproject.org/wiki/Logo

**Comment by birjolaxew** [comment]
Would we want to follow their usage guidelines, or use the infinity mark?

> #### One-color logo
> If you must use only one color, use the word design logo. Do not use the infinity logo.

Should we honor their request to ask them first?

> #### Obtaining the Fedora logo for use by graphic designers
> [...] In order to obtain properly-licensed copies of these Fedora logos, you must send a request to the logo queue at logo@fedoraproject.org. Please include a brief description of the way(s) you plan on using the logo.

Note that [other icon](http://lukas-w.github.io/font-linux/) [collections](http://fizzed.com/oss/font-mfizz/icon-fedora) use the infinity mark, with the [infinity portions](https://fedoraproject.org/wiki/File:Logo-history-threelements.jpg) removed.

I'll probably just write them an email and ask them.

**Comment by birjolaxew** [comment]
Just received a response:

> I'm sorry, I can't grant you permission to use the Fedora logo thisway.
I can bringup the idea to see if it could be approved but there's a
whole legal process for these kinds of things and it's not going to be
quick or easy. We're beholden to US trademark law.
> ~m

Looks like Fedora just straight up won't let us.

**Comment by joseluisq** [comment]
> Looks like Fedora just straight up can't let us for legal reasons.

Really it's a shame!
But... Why does it use the One-color logo?

**Comment by danleech** [comment]
@birjolaxew Thanks very much for looking into this! I’ll close this issue for now, but reopen if Fedora changes their mind/guidelines.
