### ISSUE TITLE
Request: Nginx

### ISSUE THREAD

**Issue by joseluisq** [danleech/simple-icons#413]
- https://commons.wikimedia.org/wiki/File:Nginx_logo.svg
- https://cdn-1.wp.nginx.com/wp-content/themes/nginx-theme/assets/img/nginx-favicon.png

**Comment by tomlutzenberger** [comment]
I wonder which one would be better?

**Comment by danleech** [comment]
There’s a great icon used on the NGINX website, but I can’t find an official vector source for it.

https://www.nginx.com/resources/wiki/_static/img/nginx_n_icon.png

**Comment by joseluisq** [comment]
Looks good :+1:

**Comment by kporten** [comment]
Many icons for NGINX contain only the "G", like this one:
http://fizzed.com/oss/font-mfizz/icon-nginx

**Comment by tunnckoCore** [comment]
Yea, it's probably better than the "N" inside hexagon, it feels more like "Nodejs" haha.
