### ISSUE TITLE
Request: Symfony

### ISSUE THREAD

**Issue by javiereguiluz** [danleech/simple-icons#429]
[Symfony](https://github.com/symfony/symfony) is a popular Open Source project to create web applications.

Here is the original SVG logo: https://symfony.com/logos/symfony_black_03.svg?v=5
And here are other variants and file formats: https://symfony.com/logo

Thanks for your time and consideration!

**Comment by javiereguiluz** [comment]
Thanks for adding Symfony to your collection.

**Comment by danleech** [comment]
@javiereguiluz You’re welcome!
