### ISSUE TITLE
Request: Gerrit

### ISSUE THREAD

**Issue by Greybird** [danleech/simple-icons#442]
Website: https://www.gerritcodereview.com/
Icon: https://commons.wikimedia.org/wiki/File:Gerrit_icon.svg

The icon is used as the favicon to the tool.

**Comment by birjolaxew** [comment]
Seems like their actual logo is this weird bird:

![](https://gerrit-static.storage.googleapis.com/diffy.svg)

([source](https://gerrit-review.googlesource.com/c/75842/))
