### ISSUE TITLE
Websites

### ISSUE THREAD

**Issue by matt035343** [danleech/simple-icons#68]
Make a simple icon that can be used for linking to a website og the world wide web.
Example: Et could be black with "www" or "http://" or something like that.

**Comment by danleech** [comment]
The latest version of this set is for brand icons only (with the possible exception of RSS, depending on whether you think it’s a brand). If you want a website icon I recommend The Noun Project.

https://thenounproject.com/search/?q=website

**Comment by potherca** [comment]
When you say "The latest version", am I correct in assuming that a generic "Website" icon _used_ to be available?

**Comment by danleech** [comment]
I did previously maintain a branch called “generics” that had icons for print, website, phone etc. but The Noun Project does a far better job of presenting options for those.
