### ISSUE TITLE
Microsoft Office - Done

### ISSUE THREAD

**Issue by psullivan6** [danleech/simple-icons#72]
Dan, I love the work so far and thought I'd help out as I have been working on the same kind of project. I am developing an icon font of programs, coding languages, etc... so I have some of the same and some new ones. 

Here is a link to the 3 main Microsoft Office Icons (Excel, PowerPoint, and Word): [Microsoft Office](https://dl.dropbox.com/u/30174802/Microsoft-Office.ai)

Here are their guidelines and some low-res logos: [Trademarks](http://www.microsoft.com/en-us/legal/intellectualproperty/Trademarks/EN-US.aspx)

**Comment by mrmckeb** [comment]
Will Microsoft's logo be in too? It's a super easy one, with four squares haha.

**Comment by danleech** [comment]
It’s much easier for me to close off requests if they’re listed individually. I’ll close this issue off and work from the following ones:

- #221 Excel
- #227 Microsoft
- #222 PowerPoint
- #228 Windows
- #220 Word

**Comment by mrmckeb** [comment]
Thanks @danleech. Great work on the set as a whole.
